## Once run this will define: 
## 
## OSGUTIL_FOUND       = system has OSGUTIL_PLANET lib
##
## OSGUTIL_LIBRARY     = full path to the library
##
## OSGUTIL_INCLUDE_DIR      = where to find headers 
##
## Tim Sutton


IF(APPLE)
#SET(GUI_TYPE MACOSX_BUNDLE)
#INCLUDE_DIRECTORIES ( /Developer/Headers/FlatCarbon )
FIND_LIBRARY(OSGUTIL_LIBRARY osgUtil)
MARK_AS_ADVANCED (OSGUTIL_LIBRARY)
SET(EXTRA_LIBS ${OSGUTIL_LIBRARY} )
ENDIF (APPLE)


IF (OSGUTIL_LIBRARY)
   SET(OSGUTIL_FOUND TRUE)
ENDIF (OSGUTIL_LIBRARY)

IF (OSGUTIL_FOUND)
   IF (NOT OSGUTIL_FIND_QUIETLY)
     MESSAGE(STATUS "Found OSGUTIL_PLANET: ${OSGUTIL_LIBRARY}")
   ENDIF (NOT OSGUTIL_FIND_QUIETLY)
ELSE (OSGUTIL_FOUND)
   IF (OSGUTIL_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find OSGUTIL_PLANET")
   ENDIF (OSGUTIL_FIND_REQUIRED)
ENDIF (OSGUTIL_FOUND)
