## Once run this will define: 
## 
## OSSIM_FOUND       = system has OSSIM_PLANET lib
##
## OSSIM_LIBRARY     = full path to the library
##
## OSSIM_INCLUDE_DIR      = where to find headers 
##
## Tim Sutton


IF(APPLE)
#SET(GUI_TYPE MACOSX_BUNDLE)
#INCLUDE_DIRECTORIES ( /Developer/Headers/FlatCarbon )
FIND_LIBRARY(OSSIM_LIBRARY ossim)
MARK_AS_ADVANCED (OSSIM_LIBRARY)
SET(EXTRA_LIBS ${OSSIM_LIBRARY} )
ENDIF (APPLE)


IF (OSSIM_LIBRARY)
   SET(OSSIM_FOUND TRUE)
ENDIF (OSSIM_LIBRARY)

IF (OSSIM_FOUND)
   IF (NOT OSSIM_FIND_QUIETLY)
     MESSAGE(STATUS "Found OSSIM_PLANET: ${OSSIM_LIBRARY}")
   ENDIF (NOT OSSIM_FIND_QUIETLY)
ELSE (OSSIM_FOUND)
   IF (OSSIM_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find OSSIM_PLANET")
   ENDIF (OSSIM_FIND_REQUIRED)
ENDIF (OSSIM_FOUND)
