## Once run this will define: 
## 
## OSGGA_FOUND       = system has OSGGA_PLANET lib
##
## OSGGA_LIBRARY     = full path to the library
##
## OSGGA_INCLUDE_DIR      = where to find headers 
##
## Tim Sutton


IF(APPLE)
#SET(GUI_TYPE MACOSX_BUNDLE)
#INCLUDE_DIRECTORIES ( /Developer/Headers/FlatCarbon )
FIND_LIBRARY(OSGGA_LIBRARY osgGA)
MARK_AS_ADVANCED (OSGGA_LIBRARY)
SET(EXTRA_LIBS ${OSGGA_LIBRARY} )
ENDIF (APPLE)


IF (OSGGA_LIBRARY)
   SET(OSGGA_FOUND TRUE)
ENDIF (OSGGA_LIBRARY)

IF (OSGGA_FOUND)
   IF (NOT OSGGA_FIND_QUIETLY)
     MESSAGE(STATUS "Found OSGGA_PLANET: ${OSGGA_LIBRARY}")
   ENDIF (NOT OSGGA_FIND_QUIETLY)
ELSE (OSGGA_FOUND)
   IF (OSGGA_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find OSGGA_PLANET")
   ENDIF (OSGGA_FIND_REQUIRED)
ENDIF (OSGGA_FOUND)
