## Once run this will define: 
## 
## OPENTHREADS_FOUND       = system has OPENTHREADS_PLANET lib
##
## OPENTHREADS_LIBRARY     = full path to the library
##
## OPENTHREADS_INCLUDE_DIR      = where to find headers 
##
## Tim Sutton


IF(APPLE)
#SET(GUI_TYPE MACOSX_BUNDLE)
#INCLUDE_DIRECTORIES ( /Developer/Headers/FlatCarbon )
FIND_LIBRARY(OPENTHREADS_LIBRARY OpenThreads)
MARK_AS_ADVANCED (OPENTHREADS_LIBRARY)
SET(EXTRA_LIBS ${OPENTHREADS_LIBRARY} )
ENDIF (APPLE)


IF (OPENTHREADS_LIBRARY)
   SET(OPENTHREADS_FOUND TRUE)
ENDIF (OPENTHREADS_LIBRARY)

IF (OPENTHREADS_FOUND)
   IF (NOT OPENTHREADS_FIND_QUIETLY)
     MESSAGE(STATUS "Found OPENTHREADS_PLANET: ${OPENTHREADS_LIBRARY}")
   ENDIF (NOT OPENTHREADS_FIND_QUIETLY)
ELSE (OPENTHREADS_FOUND)
   IF (OPENTHREADS_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find OPENTHREADS_PLANET")
   ENDIF (OPENTHREADS_FIND_REQUIRED)
ENDIF (OPENTHREADS_FOUND)
