## Once run this will define: 
## 
## OSSIMPLANET_QT_FOUND       = system has OSSIMPLANET_QT lib
##
## OSSIMPLANET_QT_LIBRARY     = full path to the library
##
## OSSIMPLANET_QT_INCLUDE_DIR      = where to find headers 
##
## Tim Sutton


IF(APPLE)
#SET(GUI_TYPE MACOSX_BUNDLE)
#INCLUDE_DIRECTORIES ( /Developer/Headers/FlatCarbon )
FIND_LIBRARY(OSSIMPLANET_QT_LIBRARY ossimPlanetQt)
MARK_AS_ADVANCED (OSSIM_PLANET_QT_LIBRARY)
SET(EXTRA_LIBS ${OSSIMPLANET_QT_LIBRARY} )
ENDIF (APPLE)


IF (OSSIMPLANET_QT_LIBRARY)
   SET(OSSIMPLANET_QT_FOUND TRUE)
ENDIF (OSSIMPLANET_QT_LIBRARY)

IF (OSSIMPLANET_QT_FOUND)
   IF (NOT OSSIMPLANET_QT_FIND_QUIETLY)
     MESSAGE(STATUS "Found OSSIMPLANET_QT: ${OSSIMPLANET_QT_LIBRARY}")
   ENDIF (NOT OSSIMPLANET_QT_FIND_QUIETLY)
ELSE (OSSIMPLANET_QT_FOUND)
   IF (OSSIMPLANET_QT_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find OSSIMPLANET_QT")
   ENDIF (OSSIMPLANET_QT_FIND_REQUIRED)
ENDIF (OSSIMPLANET_QT_FOUND)
