## Once run this will define: 
## 
## OSGDB_FOUND       = system has OSGDB_PLANET lib
##
## OSGDB_LIBRARY     = full path to the library
##
## OSGDB_INCLUDE_DIR      = where to find headers 
##
## Tim Sutton


IF(APPLE)
#SET(GUI_TYPE MACOSX_BUNDLE)
#INCLUDE_DIRECTORIES ( /Developer/Headers/FlatCarbon )
FIND_LIBRARY(OSGDB_LIBRARY osgDB)
MARK_AS_ADVANCED (OSGDB_LIBRARY)
SET(EXTRA_LIBS ${OSGDB_LIBRARY} )
ENDIF (APPLE)


IF (OSGDB_LIBRARY)
   SET(OSGDB_FOUND TRUE)
ENDIF (OSGDB_LIBRARY)

IF (OSGDB_FOUND)
   IF (NOT OSGDB_FIND_QUIETLY)
     MESSAGE(STATUS "Found OSGDB_PLANET: ${OSGDB_LIBRARY}")
   ENDIF (NOT OSGDB_FIND_QUIETLY)
ELSE (OSGDB_FOUND)
   IF (OSGDB_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find OSGDB_PLANET")
   ENDIF (OSGDB_FIND_REQUIRED)
ENDIF (OSGDB_FOUND)
