# ----------------------------------------------------------
# lib project generated by QMsNet (save function)
# ----------------------------------------------------------
TEMPLATE  = lib
LANGUAGE  = C++

CONFIG	 += qt warn_on debug dll

OBJECTS_DIR = tmp\obj
MOC_DIR     = tmp\moc

HEADERS   =  \
	./openModellerPluginCode.h \
	./openModellerPluginWindow.h \
	./parametersWindow.h \
	../base/PluginBase.h \
	./QLogCallback.h \
	./QOpenModeller.h \
	../../../../../src/terralib/application/qt/TeQtDatabasesListView.h \
	../../../../../src/terralib/application/qt/TeQtViewsListView.h
SOURCES   =  \
	./openModellerPluginCode.cpp \
	./openModellerPluginWindow.cpp \
	./parametersWindow.cpp \
	./QOpenModeller.cpp \
	../../../../../terralibw/ado/TeAdoDB.cpp \
	../../../../../terralibw/ado/TeAdoOracle.cpp \
	../../../../../terralibw/ado/TeAdoSqlServer.cpp \
	../../../../../src/terralib/drivers/MySQL/TeMySQL.cpp \
	../../../../../src/terralib/drivers/OracleSpatial/TeOCIConnect.cpp \
	../../../../../src/terralib/drivers/OracleSpatial/TeOCICursor.cpp \
	../../../../../src/terralib/drivers/OracleSpatial/TeOCIOracle.cpp \
	../../../../../src/terralib/drivers/OracleSpatial/TeOCISDO.cpp \
	../../../../../src/terralib/drivers/OracleSpatial/TeOracleSpatial.cpp \
	../../../../../src/terralib/drivers/PostgreSQL/TePGInterface.cpp \
	../../../../../src/terralib/drivers/PostgreSQL/TePGUtils.cpp \
	../../../../../src/terralib/drivers/PostgreSQL/TePostGIS.cpp \
	../../../../../src/terralib/drivers/PostgreSQL/TePostgreSQL.cpp \
	../../../../../src/terralib/application/qt/TeQtCheckListItem.cpp \
	../../../../../src/terralib/application/qt/TeQtDatabaseItem.cpp \
	../../../../../src/terralib/application/qt/TeQtDatabasesListView.cpp \
	../../../../../src/terralib/application/qt/TeQtViewsListView.cpp
FORMS     =  \
	./openModellerForm.ui \
	./parametersForm.ui \
	./progressForm.ui
