.TH openModellerDesktop  "January 2005" openModellerDesktop 1.0.6
.SH NAME
openModellerDesktop \- front end to the openModeller Library
.SH SYNOPSIS
.B openModellerDesktop
.SH DESCRIPTION
This manual page documents briefly the
.B openModellerDesktop
program
.PP
\fBopenModellerDesktop\fP is a front end to the openModeller fundamental
niche modelling library..
.SH OPTIONS
.TP
.B \-\-timedemo
Will give the current version of the software
.SH AUTHOR
openModellerDesktop was written by Tim Sutton <tim@linfiniti.com>
